name: "nurtimax"
description: "Cool  crypto application"
publish_to: "none"

version: 1.0.0+1

environment:
   sdk: ">=3.2.3 <4.0.0"

dependencies:
   flutter_svg: ^2.0.9
   dio: ^5.4.0
   get_it: ^7.6.7
   flutter:
      sdk: flutter
   equatable: ^2.0.5

   cupertino_icons: ^1.0.2
   flutter_bloc: ^8.1.3
   talker_flutter: ^3.6.0
   talker_dio_logger: ^2.4.0
   talker_bloc_logger: ^2.4.0
   firebase_core: ^2.24.2

dev_dependencies:
   flutter_test:
      sdk: flutter

   flutter_lints: ^2.0.0
   json_serializable: ^6.7.1
   build_runner:

flutter:
   uses-material-design: true

   assets:
      - assets/svg/
      # - images/b_dot.jpeg

   # fonts:
   #   - family: Schyler
   #     fonts:
   #       - asset: fonts/Schyler-Regular.ttf
   #       - asset: fonts/Schuler-Medium.ttf
   #         style: italic
   #   - family: Trajan Pro
   #     fonts:
   #       - asset: fonts/TrajanPro.ttf
   #       - asset: fonts/TrajanPro_Bold.ttf
   #         weight: 700
