// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9qZOafqsrfYHlIt5wjaevVND_uOKVQ0',
    appId: '1:1066791601313:web:06e80d1213548eabd8dce0',
    messagingSenderId: '1066791601313',
    projectId: 'shaped-crossbar-410916',
    authDomain: 'shaped-crossbar-410916.firebaseapp.com',
    storageBucket: 'shaped-crossbar-410916.appspot.com',
    measurementId: 'G-868J27GZ9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpeKD53QjcuC4gTupiHWbFhHccEVJYcI',
    appId: '1:1066791601313:android:2381f3ca252d8977d8dce0',
    messagingSenderId: '1066791601313',
    projectId: 'shaped-crossbar-410916',
    storageBucket: 'shaped-crossbar-410916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-uciNDZ344xIqo5FsyskM1MZt0e4SRk',
    appId: '1:1066791601313:ios:86cfe47d2ca6a3f1d8dce0',
    messagingSenderId: '1066791601313',
    projectId: 'shaped-crossbar-410916',
    storageBucket: 'shaped-crossbar-410916.appspot.com',
    iosBundleId: 'com.cryptoguys.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx-uciNDZ344xIqo5FsyskM1MZt0e4SRk',
    appId: '1:1066791601313:ios:c411dfeb6f5f747dd8dce0',
    messagingSenderId: '1066791601313',
    projectId: 'shaped-crossbar-410916',
    storageBucket: 'shaped-crossbar-410916.appspot.com',
    iosBundleId: 'com.cryptoguys.project1.RunnerTests',
  );
}
